### ISSUE TITLE
Overflow issue

### ISSUE THREAD

**Issue by flashadvocate** [ncstate/utility-bar#11]
Not sure if anyone else is running into this...

<img width="415" alt="screen shot 2016-09-20 at 4 33 00 pm" src="https://cloud.githubusercontent.com/assets/7848492/18687877/06bdaa52-7f50-11e6-9db9-5ad9ff10d233.png">

I was able to fix this locally by giving `.ncstate-utility-bar .ncstate-utility-bar-options` an `overflow: hidden;` attribute.

**Comment by apmatthews** [comment]
I've never seen it myself.

Is it only the black theme?
Is it only on certain sites?

My guess is that a general CSS rule from the site it's on that is expanding one of the search form elements. I did a quick test in the inspector with your local fix. I think it blocks the search box from showing on mobile. Could you try to track down what rule is expanding the box and address that specifically?

**Comment by flashadvocate** [comment]
@apmatthews Sorry, lost track of this. Took another look at this, and you're right, it was another stylesheet that was being used that caused the weird styling.

Sorry for the trouble. ;)
