### ISSUE TITLE
color problems with RESOURCES link

### ISSUE THREAD

**Issue by jfthomps** [ncstate/utility-bar#18]
This might be something specific to my site (VCL), but when I modify the site to use the new utility bar and hover over the RESOURCES link, I get dark red font (#900) on the same color dark red background. Foreground is coming from https://cdn.ncsu.edu/brand-assets/bootstrap/css/bootstrap.css
a:hover, a:focus {
   color: #900;
   text-decoration: none;
}
Background is coming from inline:
.ncstate-utility-bar.gray .ncstate-utility-bar-toggle a:hover {
    background-color: #900;
}

**Comment by jrchamp** [comment]
For the gray theme, you should be seeing another inline style that set the text color to white:
```
.ncstate-utility-bar a {
    color: #fff;
    text-decoration: none;
}
```

Do you have a test site you can share?

**Comment by jfthomps** [comment]
I am seeing that, but the bootstrap.css a:hover is overriding it according to Firefox.  I have a test page you can view at

https://vcl.ncsu.edu/scheduling/newbar.html

I'm using Firefox 54.0.1 on Linux.

**Comment by apmatthews** [comment]
It looks like it has to do with load order. I was able to replicate the issue locally by including bootstrap after the UB script. If bootstrap is included before the script, the colors remain correct. Order shouldn't matter though, so I'll take a look tomorrow and see what I can do about it. Thanks for reporting!

**Comment by apmatthews** [comment]
I think this is fixed via cc089573c0ca5b9ccf00a2b49318d3b830a9ec26. Your test page appears to be working properly now.

**Comment by jfthomps** [comment]
Thanks Andrew! That took care of it. When I hover now, the background darkens, but the foreground stays white. I'm seeing one other issue, but I'll post it separately.

**Comment by jfthomps** [comment]
Oops, nevermind. Doing a force reload fixed that too (it was the foreground color of the NC State Home link).
