### ISSUE TITLE
Update build system

### ISSUE THREAD

**Issue by apmatthews** [ncstate/utility-bar#26]
We're using Laravel Mix version 1.7.2. The latest version is 5.0.5. I'm not sure what it would entail, but we need to upgrade. We could also explore other approaches to building that don't rely on Laravel Mix, but I doubt that will prove to be simpler than the upgrade.

**Comment by jrchamp** [comment]
This built successfully for me: https://github.com/jrchamp/utility-bar/commit/9b3cf4c73896faf64ed4ec2285cb7eadcf3bab37
