### ISSUE TITLE
Low Contrast Error for Search Button

### ISSUE THREAD

**Issue by RichieLeahey** [ncstate/utility-bar#30]
![csserror](https://user-images.githubusercontent.com/13291191/104187980-9017e280-53e6-11eb-994a-9972de7602ca.png)

It looks like there isn't a font color defined on the button so it is using the default.

**Comment by apmatthews** [comment]
Looks like this is fixed in #28. @RichieLeahey Feel free to merge that PR and deploy to the CDN. It's only relevant to the `master` branch, so no need to worry about porting it to the `news-update` branch this time.
